apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-api-service
  labels:
    app: multi-cloud-api
spec:
  type: LoadBalancer
  selector:
    app: multi-cloud-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
